Consolidate handling of smaple data
BrownBiomechanics/Autoscoper pull request #29
Opened 2022-08-29 15:34 UTC by NicerNewerCar

* Move all uses of sample data to top level CMakeLists
* Add option Autoscoper_INSTALL_SAMPLE_DATA
* Change file calls to install calls
* Closes #27

2022-08-29 21:08 UTC, jcfr requested changes

2022-09-02 21:29 UTC, jcfr approved these changes

2022-09-02 21:30 UTC, jcfr commented
@NicerNewerCar Could you test that sample_data can be loaded when running `autoscoper.exe` from either a build or install tree on Windows :pray:

2022-09-06 12:17 UTC, NicerNewerCar commented
@jcfr The sample_data can be loaded from either tree

2022-09-27 15:11 UTC, merged