BUG: Fix tab order in tracking dialog UI
BrownBiomechanics/Autoscoper pull request #292
Opened 2024-08-06 18:59 UTC by NicerNewerCar

Closes #288 
![tabbing](https://github.com/user-attachments/assets/8ab9caa3-986e-4ba3-9faf-720f31894b5e)

2024-08-08 18:48 UTC, amymmorton approved these changes

2024-08-12 16:51 UTC, DajungYoon approved these changes

2024-08-12 19:44 UTC, jcfr requested changes
So that we maintain the history associated with the ui files independently of the tab order change, consider instead using the feature `Edit -> Tab Orders` from Qt Designer:

![image](https://github.com/user-attachments/assets/8067ba0a-f495-4a04-8181-5a6f1bdf82b4)

Once the tab order has been updated, change should be similar to the following:

![image](https://github.com/user-attachments/assets/718d3014-88d9-4163-840d-b42b97d27e88)

2024-08-19 14:04 UTC, jcfr approved these changes

2024-08-19 14:04 UTC, merged