DOC: Include description of pre-processing transforms
BrownBiomechanics/Autoscoper pull request #300
Opened 2024-09-06 16:01 UTC by NicerNewerCar

Closes #280 

TODO:
- [ ] Bring over images

2024-09-06 23:10 UTC, jcfr requested changes

2024-09-06 23:10 UTC, jcfr commented on Documentation/transforms.md
> +        W -- bone_PVOL2AUT.tfm --> M
And here is revisited version where we can describe each space by a subgraph:

```
flowchart TD
    subgraph image_space["Image Space"]
      tiff["TIFF"]
    end
    subgraph dicom_space["DICOM Space"]
      transformed_pvol["Spatially located PV"]
    end
    subgraph world_space["World Space"]
      world_origin["World origin"]
      partial_volume["Partial Volume (PVOL)"]
    end
    subgraph aut_space["Autoscoper Space (AUT)"]
      model["Model"]
    end
    world_space -- "{bone}_t.tfm" --> dicom_space
    image_space -- "{bone}.tfm" --> dicom_space
    image_space -- "{bone}_scale.tfm" --> world_space
    image_space -- "{bone}_DICOM2AUT.tfm" --> aut_space
    world_space -- "{bone}_PVOL2AUT.tfm" --> aut_space
```

```mermaid
flowchart TD
    subgraph image_space["Image Space"]
      tiff["TIFF"]
    end
    subgraph dicom_space["DICOM Space"]
      transformed_pvol["Spatially located PV"]
    end
    subgraph world_space["World Space"]
      world_origin["World origin"]
      partial_volume["Partial Volume (PVOL)"]
    end
    subgraph aut_space["Autoscoper Space (AUT)"]
      model["Model"]
    end
    world_space -- "{bone}_t.tfm" --> dicom_space
    image_space -- "{bone}.tfm" --> dicom_space
    image_space -- "{bone}_scale.tfm" --> world_space
    image_space -- "{bone}_DICOM2AUT.tfm" --> aut_space
    world_space -- "{bone}_PVOL2AUT.tfm" --> aut_space
```

2024-09-09 17:23 UTC, NicerNewerCar commented on Documentation/transforms.md
> +is tracked, and the relative motion of one rigid body is calculated with respect to a reference.
I believe this is another rigid body.

2024-11-22 15:11 UTC, amymmorton approved these changes

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +matrix converts between RAS and LPS coordinates:
```suggestion
When reading or writing files, Slicer automatically converts between RAS and LPS
coordinate systems as needed. This conversion involves flipping the sign of the first
two coordinate axes. The transformation matrix for converting between RAS and LPS
coordinates is shown below:
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +Transforming between image space and world space results in proportional changes in the image volume:
```suggestion
Spatial referencing defines the relationship between voxel coordinates in image space
and their corresponding positions in world space. This includes encoding voxel-to-world
unit resolution (also known as pixel/voxel spacing), the origin, and orientation of the
dataset.

In the DICOM format, spatial referencing information is embedded in the DICOM header
metadata. In MATLAB, the [`imref3d`](https://www.mathworks.com/help/images/ref/imref3d.html) function can be constructed
using this metadata to store the intrinsic spatial relationships.

Transforming data between image space and world space involves proportional adjustments
to the image volume, as shown in the matrix below:
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +each axis, and `O_{x,y,z}` is the origin for each respective dimension.
```suggestion
In the matrix shown above, `P_{x,y,z}` represents the pixel spacing along each axis, while `O_{x,y,z}` defines the origin for each dimension.
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +header metadata in the DICOM header. Note the RAS anatomical orientation and +X, +Y, +Z (red/green/blue) axes indicators.
```suggestion
When importing DICOM data into 3D Slicer, a spatial referencing transform is automatically applied to the CT image volume.
This transform is derived from the DICOM header metadata and aligns the data to Slicer’s RAS anatomical orientation system,
with the +X, +Y, and +Z directions corresponding to the red, green, and blue axes, respectively.
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +Volumes module.
```suggestion
The spatial referencing information of a volume in Slicer can be inspected in the **Volume Information** section of the **Volumes** module. This provides detailed metadata, including spacing, origin, and orientation.
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +following structure outlines the information in the output directory:
```suggestion
### Output Directory Structure

During partial volume generation, SlicerAutoscoperM creates several folders in the output directory. These folders store the models, volumes, transforms, and tracking information required for processing. The structure is as follows:
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +
```suggestion

**Folder Descriptions:**
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +
```suggestion

### Visualizing Transformations

The following diagrams illustrate the transformations between spaces:
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +
```suggestion
### Transformation Workflow

The relationships between image, world, and Autoscoper spaces are illustrated below:
```

2024-11-25 15:30 UTC, jcfr commented on Documentation/transforms.md
> +orientation. In Autoscoper, the voxel resolution of TIFF volumes follows a specified axes.
```suggestion
### Pre-Processing and Volume Generation

In the Pre-processing tab of the SlicerAutoscoperM module, rigid bodies of interest can
be automatically segmented from a CT DICOM volume. Alternatively, previously generated segmentations
can be loaded. These segmentations are used to generate partial volumes, isolating the density data
within the bounds of the segmented model. The partial volume is saved as a TIFF stack, which is later imported into Autoscoper in a specific orientation referred to as Autoscoper (AUT) space.

Within Autoscoper, this TIFF stack is used to generate Digitally Reconstructed Radiographs (DRRs)
by projecting the density data onto the target image plane, where it is overlaid with the radiographs for each frame.

TIFF stacks, like CT DICOM volumes, originate in image space and require a
spatial referencing transform to encode their world location, spacing, and
orientation. In Autoscoper, the voxel resolution of TIFF volumes aligns with predefined axes.
```

2024-11-26 15:55 UTC, amymmorton commented on Documentation/transforms.md
> +is tracked, and the relative motion of one rigid body is calculated with respect to a reference.
@jcfr have these been addressed? Can we commit and make live please?

2025-01-06 15:50 UTC, jcfr approved these changes

2025-01-06 15:51 UTC, merged