CI for Configuration and Building
BrownBiomechanics/Autoscoper pull request #67
Opened 2022-12-19 22:26 UTC by NicerNewerCar

2022-12-19 23:10 UTC, jcfr requested changes

2022-12-19 23:10 UTC, jcfr commented on .github/workflows/ci.yml
> +name: CI - Ubuntu
```suggestion
name: CI
```

2022-12-19 23:10 UTC, jcfr commented on .github/workflows/ci.yml
> +name: CI - Ubuntu
System being used for testing will be part of the job name

2022-12-19 23:10 UTC, jcfr commented on .github/workflows/ci.yml
> +    - name: Install CUDA
```suggestion
    - name: Install CUDA
      if: ${{ matrix.rendering_backend == 'CUDA' }}
      uses: Jimver/cuda-toolkit@v0.2.8
```

This assumes the matrix will be defined using something like this


```yaml
jobs:
  autoscoper:
    strategy:
      matrix:
        rendering_backend: ['CUDA', 'OpenCL']
    steps:
      ....
```

2022-12-20 14:32 UTC, jcfr commented on .github/workflows/ci.yml
> +        setup-python: false
```suggestion
        version: ${{ env.QT_VERSION }}
        host: linux
        target: desktop
        arch: gcc_64
        dir: /opt/qt
        setup-python: false
```

2022-12-20 14:44 UTC, jcfr commented on .github/workflows/ci.yml
> +      uses: Jimver/cuda-toolkit@v0.2.8
```suggestion
      uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '10.1'
```

2022-12-20 14:46 UTC, jcfr commented on .github/workflows/ci.yml
> +      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAutoscoper_RENDERING_BACKEND=${{matrix.rendering_backend}} -DAutoscoper_SUPERBUILD=ON
```suggestion
      run: |
        cmake \
          -S ${{github.workspace}} \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DAutoscoper_RENDERING_BACKEND=${{matrix.rendering_backend}} \
          -DAutoscoper_SUPERBUILD=ON
```

See https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines

2022-12-20 14:47 UTC, jcfr commented on .github/workflows/ci.yml
> +      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
```suggestion
      run: |
        cmake \
          --build ${{github.workspace}}/build \
          --config ${{env.BUILD_TYPE}}
```

2022-12-20 14:48 UTC, jcfr commented on .github/workflows/ci.yml
> +
```suggestion
```

2022-12-20 14:49 UTC, jcfr commented on .github/workflows/ci.yml
> +# This pipe line will be triggered when a pull request is created and will validiate that the CUDA and OpenCL versions of Autoscoper can configure and build successfully.
```suggestion
```

2022-12-20 18:30 UTC, NicerNewerCar commented
@jcfr Got the build working for windows, see [CI #16](https://github.com/BrownBiomechanics/Autoscoper/actions/runs/3742604265), the build on ubuntu is failing it looks like the version of opengl that github has on there runners does not work with glew see [CI #13](https://github.com/BrownBiomechanics/Autoscoper/actions/runs/3741892663/jobs/6352106123). 

We also cannot run ubuntu and windows from the same script because there are a couple differences between the two( ` to split line on windows vs \ to split line on ubuntu, and using a difference compiler on the two OSs)

Note: This pipeline takes > 1 hour to run, there are 2,000 minutes/month included for free with github and Windows runners consume 2x the minutes of linux runners (ie. 10 minutes on a windows runner is equivalent to 20 minutes on a linux runner).

See [About billing for GitHub Actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

2024-01-17 16:02 UTC, NicerNewerCar commented
Closing this since we are using [SA^M](https://github.com/BrownBiomechanics/SlicerAutoscoperM) to perform CI

2024-01-17 16:02 UTC, closed without merging